// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPeAqvixAhut3IwZb49nRtwYZCLWyoTRs',
    appId: '1:385723574922:web:39a569238d0df266bb5b73',
    messagingSenderId: '385723574922',
    projectId: 'mad2026-flutter-app',
    authDomain: 'mad2026-flutter-app.firebaseapp.com',
    storageBucket: 'mad2026-flutter-app.firebasestorage.app',
    measurementId: 'G-KHTZ7CY4DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByeWjjUNhW7TIo5_V3MMaQctr4ORBZSpg',
    appId: '1:385723574922:android:bbaec89ce4a8a5b3bb5b73',
    messagingSenderId: '385723574922',
    projectId: 'mad2026-flutter-app',
    storageBucket: 'mad2026-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByVqLAaILbj0tpg1VaT6sWie9QErV0DKM',
    appId: '1:385723574922:ios:49134dd1ec184684bb5b73',
    messagingSenderId: '385723574922',
    projectId: 'mad2026-flutter-app',
    storageBucket: 'mad2026-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.mad2026flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByVqLAaILbj0tpg1VaT6sWie9QErV0DKM',
    appId: '1:385723574922:ios:49134dd1ec184684bb5b73',
    messagingSenderId: '385723574922',
    projectId: 'mad2026-flutter-app',
    storageBucket: 'mad2026-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.mad2026flutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPeAqvixAhut3IwZb49nRtwYZCLWyoTRs',
    appId: '1:385723574922:web:476c096a3af09cdabb5b73',
    messagingSenderId: '385723574922',
    projectId: 'mad2026-flutter-app',
    authDomain: 'mad2026-flutter-app.firebaseapp.com',
    storageBucket: 'mad2026-flutter-app.firebasestorage.app',
    measurementId: 'G-JVLGC121XC',
  );
}
